# Generated by Django 4.1.3 on 2025-05-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='Sabit-Kalmali', unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='Sabit-Kalmali', unique=True),
        ),
    ]
