# Generated by Django 4.1.3 on 2025-06-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_slug_alter_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='images',
            field=models.ImageField(upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='Otomatik-Doldurulacaktır', unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='images',
            field=models.ImageField(upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='Otomatik-Doldurlacaktır', unique=True),
        ),
    ]
