# Generated by Django 4.1.3 on 2025-05-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='featured_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('images', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('isActive', models.BooleanField()),
                ('slug', models.SlugField(default='', unique=True)),
            ],
        ),
    ]
