# Generated by Django 4.1.3 on 2025-05-31 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kavraz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='featured_products',
        ),
    ]
